name = "recipes"
type = "javascript"
account_id = "1ce2ff3c44486eee64a00ddf867de4e0"
workers_dev = true
route = ""
zone_id = ""
[build.upload]
dir="src"
format = "modules"
main = "./index.js"
[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
